[package]
name = "vn-tilemap"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
vn-ui = { path = "../vn-ui" }
vn-scene = { path = "../vn-scene" }
log = { workspace = true }