[package]
name = "vn-vttrpg"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vn-vttrpg-window = { path = "../vn-vttrpg-window" }
env_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
console_error_panic_hook = {workspace = true}
console_log = {workspace = true}
