[package]
name = "vn-vttrpg"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vn-vttrpg-window = { path = "../vn-vttrpg-window" }
log = { workspace = true }
anyhow = { workspace = true }
